import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  handwritingTitle: {
    fontSize: 50,
    fontFamily: 'DancingScript-Bold',
    color: '#000000',
    textAlign: 'center',
    marginTop: 40,
    marginBottom: 8,
  },
  subHeader: {
    fontSize: 24,
    color: '#000000',
    textAlign: 'center',
    marginBottom: 16,
  },
  totalRaised: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#000000',
    textAlign: 'center',
    marginBottom: 20,
  },
  qrLabel: {
    fontSize: 20,
    color: '#000000',
    marginBottom: 8,
  },
  qrText: {
    fontSize: 20,
    color: '#000000',
    marginTop: 8,
    textAlign: 'center',
  },
  donationCard: {
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    padding: 12,
    marginHorizontal: 20,
    marginVertical: 8,
  },
  image: {
    width: '100%',
    height: 200,
    borderRadius: 10,
    marginBottom: 10,
  },
  message: {
    fontSize: 20,
    color: '#ffffff',
    marginBottom: 4,
  },
  amount: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fffffff',
  },
  viewGiftsButton: {
    marginTop: 4,
    marginHorizontal: 20,
    backgroundColor: '#8e94f2',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    width: '80%',
  },
  viewGiftsButtonText: {
    color: '#ffffff',
    fontWeight: 'bold',
    fontSize: 20,
  },
  label: {
    fontSize: 20,
    color: '#ffffff',
    marginBottom: 10,
    marginLeft: 20,
  },
  input: {
    backgroundColor: '#ffffff',
    padding: 12,
    borderRadius: 8,
    marginHorizontal: 20,
    marginBottom: 10,
    color: '#000000',
  },
  button: {
    backgroundColor: '#cbe6c7',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    marginTop: 8,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    width: '80%',
  },
  buttonText: {
    color: '#fff',
    fontSize: 20,
    fontFamily: 'Poppins-SemiBold',
    textAlign: 'center',
  },
  homeButton: {
    marginTop: 8,
    padding: 12,
    backgroundColor: '#ccc',
    borderRadius: 8,
    alignItems: 'center',
    alignSelf: 'center',
    width: 80,
  },
  homeButtonText: {
    color: '#333',
    fontSize: 16,
  },
});

