import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flexGrow: 1,
    padding: 40,
    justifyContent: 'flex-start',
  },
  title: {
    fontSize: 34,
    fontWeight: '600',
    color: '#ffffff',
    textAlign: 'center',
    marginTop: 40,
    marginBottom: 20,
    fontFamily: 'Poppins-Bold',
  },
  sectionTitle: {
    fontSize: 20,
    color: '#1bfff3',
    fontWeight: '700',
    marginTop: 50,
    marginBottom: 50,
    fontFamily: 'Poppins-Bold',
  },
  label: {
    fontSize: 30,
    fontWeight: '500',
    color: '#000000',
    marginTop: 30,
    fontFamily: 'Poppins-SemiBold',
  },
  value: {
    fontSize: 20,
    color: '#1bfff3',
    fontFamily: 'Poppins-Regular',
  },
  messageBox: {
    fontSize: 20,
    color: '#1bfff3',
    backgroundColor: '#F8F8F8',
    padding: 12,
    borderRadius: 8,
    marginTop: 4,
    fontFamily: 'Poppins-Regular',
  },
  code: {
    fontSize: 20,
    color: '#977dff',
    fontWeight: 'bold',
    marginTop: 4,
    fontFamily: 'Poppins-Bold',
  },
  note: {
    fontSize: 20,
    color: '#555',
    textAlign: 'center',
    marginTop: 30,
    marginBottom: 40,
    fontFamily: 'Poppins-Regular',
  },
  button: {
    backgroundColor: '#8e94f2',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 40,
    alignItems: 'center',
    width: '100%',
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
  },
});