import { StyleSheet, Dimensions } from 'react-native';

const screenWidth = Dimensions.get('window').width;

export default StyleSheet.create({
  scrollContainer: {
    padding: 20,
    paddingBottom: 60,
    alignItems: 'center',
  },
  title: {
    fontSize: 32,
    fontWeight: '600',
    color: '#000000',
    textAlign: 'center',
    marginTop: 80,
    marginBottom: 30,
    fontFamily: 'Poppins-Bold',
  },
  input: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    padding: 15,
    borderRadius: 10,
    fontSize: 20,
    marginBottom: 20,
    fontFamily: 'Poppins-Regular',
    width: '100%',
  },
  inputMessage: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    padding: 15,
    borderRadius: 10,
    fontSize: 20,
    marginBottom: 20,
    fontFamily: 'Poppins-Regular',
    textAlignVertical: 'top',
    width: '100%',
    minHeight: 100,
  },
  amountOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
    marginVertical: 20,
    width: '100%',
  },
  amountButton: {
    width: '48%',
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  amountButtonSelected: {
    borderWidth: 2,
    borderColor: '#8e94f2',
  },
  amountButtonText: {
    fontSize: 18,
    fontFamily: 'Poppins-Medium',
    color: '#000',
  },
  amountButtonTextSelected: {
    fontWeight: '600',
    color: '#000',
  },
  photoButton: {
    marginTop: 20,
    marginBottom: 10,
    paddingVertical: 12,
    paddingHorizontal: 30,
    backgroundColor: '#e3e3e3',
    borderRadius: 30,
  },
  photoButtonText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 16,
    color: '#333',
  },
  preview: {
    width: screenWidth - 40,
    height: 200,
    borderRadius: 16,
    marginBottom: 20,
  },
  button: {
    backgroundColor: '#8e94f2',
    paddingVertical: 18,
    borderRadius: 20,
    alignItems: 'center',
    width: screenWidth - 48,
    alignSelf: 'center',
    marginTop: 10,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Poppins-SemiBold',
  },
homeButton: {
  marginTop: 16,
  padding: 12,
  backgroundColor: '#ccc',
  borderRadius: 8,
  alignItems: 'center',
  alignSelf: 'center',
  width: 80,
},
homeButtonText: {
  color: '#333',
  fontSize: 16,
},
});
